services:

  myshop:
    container_name: shop
    restart: on-failure
    build: shop-app/.
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres:5432/shop
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      REDIS_USER: redis
      REDIS_USER_PASSWORD: redispass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PAYMENT_API_URL: http://payment:8081
    networks:
      - shop-net
    depends_on:
      postgres:
        condition: service_healthy
      payment-service:
        condition: service_started
      redis:
        condition: service_healthy

  payment-service:
    container_name: payment
    restart: on-failure
    build: payment-service/.
    ports:
      - "8081:8081"
    networks:
      - shop-net

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5433:5432"
    networks:
      - shop-net
    volumes:
      - postgres-data:/var/lib/posgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    environment:
      REDIS_PASSWORD: password
      REDIS_USER: redis
      REDIS_USER_PASSWORD: redispass
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - shop-net
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass password" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user redis on >redispass ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
networks:
  shop-net: