logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          shop-client:
            registration:
              client-id: shop-client
              client-secret: "{noop}shop-secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - refresh_token
                - client_credentials
              scopes:
                - openid
                - balance