logging:
  level:
    org.springframework.security: trace

server:
  port: 8082

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          shop-client:
            registration:
              client-name: shop-client
              client-id: shop-client
              client-secret: ${SHOP_OAUTH_SECRET:"{noop}shop-secret"}
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - payment