server:
  port: 8080

spring:
  application:
    name: myshop

  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/shop}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
