server:
  port: 8080

spring:
  application:
    name: myshop

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_URL:localhost:5432/shop}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  liquibase:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/shop}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      username: ${REDIS_USER:redis}
      password: ${REDIS_USER_PASSWORD:redispass}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/

  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: ${ISSUER_URL:http://localhost:8082}
        registration:
          shop-client:
            provider: spring
            client-id: shop-client
            client-secret: ${SHOP_OAUTH_SECRET:shop-secret}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: payment


app:
  payment:
    url: ${PAYMENT_API_URL:http://localhost:8081}